import { db } from "@workspace/db";
import { plantsTable } from "@workspace/db";
import { sql } from "drizzle-orm";

const plantsData = [
  // Tropical
  { name: "Monstera Deliciosa", scientificName: "Monstera deliciosa", price: "68.00", category: "Tropical", difficulty: "Easy", lightRequirement: "Bright indirect", wateringFrequency: "Weekly", petSafe: false, airPurificationRating: 4, indoor: true, description: "The iconic split-leaf plant that defines modern interiors. Each leaf is a masterpiece of natural design with dramatic fenestrations.", careInstructions: "Water when top 2 inches of soil are dry. Clean leaves monthly. Provide a moss pole for climbing.", recommendedPlacement: "Living room corner, 5-8 feet from window", growthSpeed: "Moderate", humidityRequirement: "Medium", emoji: "🌿", gradient: "from-emerald-400/20 to-green-600/10", badge: "Bestseller", popularity: 95 },
  { name: "Fiddle Leaf Fig", scientificName: "Ficus lyrata", price: "95.00", originalPrice: "120.00", category: "Statement", difficulty: "Moderate", lightRequirement: "Bright indirect", wateringFrequency: "Bi-weekly", petSafe: false, airPurificationRating: 3, indoor: true, description: "A dramatic statement plant with large violin-shaped leaves. Commands attention as a living sculpture in any space.", careInstructions: "Keep in consistent light, avoid drafts. Water thoroughly then let dry. Wipe leaves monthly.", recommendedPlacement: "Well-lit corner, away from heating vents", growthSpeed: "Slow", humidityRequirement: "Medium", emoji: "🌱", gradient: "from-lime-400/20 to-emerald-600/10", badge: "Premium", popularity: 88 },
  { name: "Pothos Golden", scientificName: "Epipremnum aureum", price: "28.00", category: "Trailing", difficulty: "Easy", lightRequirement: "Low to bright indirect", wateringFrequency: "Weekly", petSafe: false, airPurificationRating: 5, indoor: true, description: "The ultimate beginner plant. Cascading heart-shaped leaves bring life to any shelf or hanging basket.", careInstructions: "Water when soil feels dry. Trim regularly to encourage bushiness. Propagates easily in water.", recommendedPlacement: "Shelves, hanging baskets, table edges", growthSpeed: "Fast", humidityRequirement: "Low", emoji: "🪴", gradient: "from-yellow-400/20 to-lime-600/10", badge: "New Arrival", popularity: 92 },
  { name: "Snake Plant", scientificName: "Sansevieria trifasciata", price: "42.00", originalPrice: "55.00", category: "Succulent", difficulty: "Easy", lightRequirement: "Any light", wateringFrequency: "Monthly", petSafe: false, airPurificationRating: 5, indoor: true, description: "Nearly indestructible and strikingly architectural. Converts CO2 to oxygen at night, perfect for bedrooms.", careInstructions: "Water sparingly, less in winter. Tolerates neglect. Never let sit in waterlogged soil.", recommendedPlacement: "Bedroom, office, low-light corners", growthSpeed: "Slow", humidityRequirement: "Low", emoji: "🌵", gradient: "from-teal-400/20 to-cyan-600/10", popularity: 97 },
  { name: "Pink Princess Philodendron", scientificName: "Philodendron erubescens", price: "145.00", category: "Rare", difficulty: "Moderate", lightRequirement: "Bright indirect", wateringFrequency: "Weekly", petSafe: false, airPurificationRating: 4, indoor: true, description: "A collector's dream with stunning pink variegation. Each leaf is uniquely patterned — no two are alike.", careInstructions: "Bright indirect light for best variegation. Water when top inch dries. High humidity preferred.", recommendedPlacement: "Bright rooms, near east-facing windows", growthSpeed: "Moderate", humidityRequirement: "High", emoji: "🌸", gradient: "from-pink-400/20 to-rose-600/10", badge: "Rare Find", popularity: 78 },
  { name: "Bird of Paradise", scientificName: "Strelitzia reginae", price: "120.00", category: "Tropical", difficulty: "Moderate", lightRequirement: "Full sun to bright indirect", wateringFrequency: "Weekly", petSafe: false, airPurificationRating: 3, indoor: true, description: "Commanding presence with enormous paddle-shaped leaves. Creates instant tropical ambiance.", careInstructions: "Needs bright light for best growth. Water deeply, then allow to partially dry. Feed monthly in growing season.", recommendedPlacement: "South or west-facing windows, sunrooms", growthSpeed: "Slow", humidityRequirement: "Medium", emoji: "🌴", gradient: "from-orange-400/20 to-amber-600/10", badge: "Popular", popularity: 85 },
  { name: "Peace Lily", scientificName: "Spathiphyllum wallisii", price: "35.00", category: "Flowering", difficulty: "Easy", lightRequirement: "Low to medium indirect", wateringFrequency: "Weekly", petSafe: false, airPurificationRating: 5, indoor: true, description: "Elegant white blooms and glossy leaves that thrive in low light. One of the best air purifiers available.", careInstructions: "Keep soil consistently moist. Drooping is its way of asking for water. Remove spent blooms.", recommendedPlacement: "Bathrooms, bedrooms, offices", growthSpeed: "Moderate", humidityRequirement: "High", emoji: "🌺", gradient: "from-white/20 to-gray-200/10", badge: "Bestseller", popularity: 91 },
  { name: "Rubber Plant", scientificName: "Ficus elastica", price: "55.00", category: "Statement", difficulty: "Easy", lightRequirement: "Medium to bright indirect", wateringFrequency: "Bi-weekly", petSafe: false, airPurificationRating: 4, indoor: true, description: "Glossy burgundy and green leaves create a bold architectural statement. Grows tall and impressive over time.", careInstructions: "Wipe leaves to maintain shine. Water when top inch dries. Can tolerate some direct morning sun.", recommendedPlacement: "Living rooms, entryways, bright corners", growthSpeed: "Moderate", humidityRequirement: "Medium", emoji: "🍂", gradient: "from-red-400/20 to-rose-600/10", popularity: 82 },
  { name: "Calathea Orbifolia", scientificName: "Calathea orbifolia", price: "48.00", category: "Statement", difficulty: "Moderate", lightRequirement: "Medium indirect", wateringFrequency: "Weekly", petSafe: true, airPurificationRating: 3, indoor: true, description: "Stunning silver-green striped leaves that move with the light cycle. A true living artwork.", careInstructions: "Use filtered or rainwater. Loves humidity — mist or use a humidifier. No direct sun.", recommendedPlacement: "Bathrooms, kitchens, humid rooms", growthSpeed: "Slow", humidityRequirement: "High", emoji: "🌀", gradient: "from-emerald-300/20 to-teal-500/10", badge: "Pet Safe", popularity: 75 },
  { name: "String of Pearls", scientificName: "Senecio rowleyanus", price: "32.00", category: "Trailing", difficulty: "Moderate", lightRequirement: "Bright indirect to some direct", wateringFrequency: "Bi-weekly", petSafe: false, airPurificationRating: 2, indoor: true, description: "Cascading chains of perfect pearl-like leaves. A mesmerizing conversation piece for any shelf.", careInstructions: "Fast-draining soil is essential. Water sparingly — pearls should look plump, not wrinkled.", recommendedPlacement: "High shelves, hanging planters near windows", growthSpeed: "Moderate", humidityRequirement: "Low", emoji: "🫧", gradient: "from-green-300/20 to-lime-500/10", popularity: 72 },
  // More plants
  { name: "ZZ Plant", scientificName: "Zamioculcas zamiifolia", price: "45.00", category: "Tropical", difficulty: "Easy", lightRequirement: "Low to bright indirect", wateringFrequency: "Monthly", petSafe: false, airPurificationRating: 4, indoor: true, description: "Virtually indestructible with glossy, waxy leaves. Thrives on neglect and low light conditions.", careInstructions: "Water every 2-3 weeks, even less in winter. Do not overwater — rhizomes store water.", recommendedPlacement: "Offices, dark corners, bathrooms", growthSpeed: "Slow", humidityRequirement: "Low", emoji: "🌿", gradient: "from-emerald-500/20 to-green-700/10", popularity: 90 },
  { name: "Chinese Money Plant", scientificName: "Pilea peperomioides", price: "25.00", category: "Small", difficulty: "Easy", lightRequirement: "Bright indirect", wateringFrequency: "Weekly", petSafe: true, airPurificationRating: 3, indoor: true, description: "Charming coin-shaped leaves on slender stems. Produces baby offsets freely — perfect for sharing.", careInstructions: "Rotate weekly for even growth. Water when top inch dries. Propagate offshoots in water.", recommendedPlacement: "Windowsills, desktops, shelves", growthSpeed: "Moderate", humidityRequirement: "Medium", emoji: "🪙", gradient: "from-lime-300/20 to-green-500/10", badge: "Pet Safe", popularity: 80 },
  { name: "Aloe Vera", scientificName: "Aloe barbadensis miller", price: "22.00", category: "Succulent", difficulty: "Easy", lightRequirement: "Bright indirect to direct", wateringFrequency: "Monthly", petSafe: false, airPurificationRating: 3, indoor: true, description: "The healing plant. Soothing gel inside the thick leaves is great for minor burns and skin care.", careInstructions: "Full sun or bright light. Water deeply but infrequently. Excellent drainage is essential.", recommendedPlacement: "Kitchen windowsill, sunny spots", growthSpeed: "Slow", humidityRequirement: "Low", emoji: "🌵", gradient: "from-green-400/20 to-emerald-600/10", badge: "Bestseller", popularity: 94 },
  { name: "Philodendron Heartleaf", scientificName: "Philodendron hederaceum", price: "20.00", category: "Trailing", difficulty: "Easy", lightRequirement: "Low to medium indirect", wateringFrequency: "Weekly", petSafe: false, airPurificationRating: 4, indoor: true, description: "Heart-shaped glossy leaves cascade beautifully. One of the most forgiving houseplants available.", careInstructions: "Water when top inch dries. Mist occasionally. Pinch back for fuller growth.", recommendedPlacement: "Hanging baskets, shelves, tables", growthSpeed: "Fast", humidityRequirement: "Medium", emoji: "💚", gradient: "from-green-300/20 to-emerald-500/10", popularity: 89 },
  { name: "Areca Palm", scientificName: "Dypsis lutescens", price: "75.00", category: "Tropical", difficulty: "Moderate", lightRequirement: "Bright indirect", wateringFrequency: "Weekly", petSafe: true, airPurificationRating: 5, indoor: true, description: "Elegant feathery fronds create a resort-like atmosphere. Among the best natural humidifiers.", careInstructions: "Keep soil lightly moist. Flush with water monthly. Sensitive to fluoride — use filtered water.", recommendedPlacement: "Living rooms, bright hallways, offices", growthSpeed: "Moderate", humidityRequirement: "High", emoji: "🌴", gradient: "from-yellow-300/20 to-lime-500/10", badge: "Pet Safe", popularity: 76 },
  { name: "Pothos Marble Queen", scientificName: "Epipremnum aureum 'Marble Queen'", price: "30.00", category: "Trailing", difficulty: "Easy", lightRequirement: "Medium to bright indirect", wateringFrequency: "Weekly", petSafe: false, airPurificationRating: 5, indoor: true, description: "Stunning white and green variegated leaves trail gracefully. More light = more variegation.", careInstructions: "More light preserves variegation. Water when dry. Easy to propagate in water.", recommendedPlacement: "Bright shelves, hanging baskets", growthSpeed: "Moderate", humidityRequirement: "Medium", emoji: "🌿", gradient: "from-slate-300/20 to-emerald-400/10", popularity: 83 },
  { name: "Dracaena Marginata", scientificName: "Dracaena marginata", price: "58.00", category: "Statement", difficulty: "Easy", lightRequirement: "Medium indirect", wateringFrequency: "Bi-weekly", petSafe: false, airPurificationRating: 4, indoor: true, description: "Architectural canes topped with spiky red-edged leaves. Adds sculptural drama to any interior.", careInstructions: "Allow soil to dry between waterings. Trim brown tips. Avoid fluoride — use filtered water.", recommendedPlacement: "Corners, entryways, bright rooms", growthSpeed: "Slow", humidityRequirement: "Low", emoji: "🌱", gradient: "from-red-300/20 to-rose-500/10", popularity: 79 },
  { name: "Boston Fern", scientificName: "Nephrolepis exaltata", price: "32.00", category: "Fern", difficulty: "Moderate", lightRequirement: "Indirect light", wateringFrequency: "Twice weekly", petSafe: true, airPurificationRating: 5, indoor: true, description: "Lush cascading fronds that love humidity. One of the best air purifiers and moisture regulators.", careInstructions: "Keep soil consistently moist. Mist daily or use a pebble tray. High humidity is key.", recommendedPlacement: "Bathrooms, kitchens, humid spaces", growthSpeed: "Moderate", humidityRequirement: "High", emoji: "🌿", gradient: "from-green-400/20 to-teal-600/10", badge: "Pet Safe", popularity: 73 },
  { name: "Jade Plant", scientificName: "Crassula ovata", price: "28.00", category: "Succulent", difficulty: "Easy", lightRequirement: "Bright indirect to some direct", wateringFrequency: "Bi-weekly", petSafe: false, airPurificationRating: 2, indoor: true, description: "Believed to bring good luck and prosperity. Thick oval leaves on woody stems — stunning when mature.", careInstructions: "Water sparingly, allow to dry completely. Bright light for compact growth. Feed lightly in summer.", recommendedPlacement: "Sunny windowsills, office desks", growthSpeed: "Slow", humidityRequirement: "Low", emoji: "🌿", gradient: "from-emerald-400/20 to-green-600/10", popularity: 81 },
  { name: "Orchid Phalaenopsis", scientificName: "Phalaenopsis amabilis", price: "55.00", category: "Flowering", difficulty: "Moderate", lightRequirement: "Bright indirect", wateringFrequency: "Weekly", petSafe: true, airPurificationRating: 2, indoor: true, description: "Elegant blooms that last months. With proper care, reblooms year after year in stunning displays.", careInstructions: "Water weekly, let dry between. Fertilize with orchid food monthly. Needs temperature drop to rebloom.", recommendedPlacement: "Windowsills, dining tables, desks", growthSpeed: "Slow", humidityRequirement: "Medium", emoji: "🌸", gradient: "from-purple-300/20 to-violet-500/10", badge: "Premium", popularity: 86 },
  { name: "Prayer Plant", scientificName: "Maranta leuconeura", price: "26.00", category: "Small", difficulty: "Easy", lightRequirement: "Low to medium indirect", wateringFrequency: "Weekly", petSafe: true, airPurificationRating: 3, indoor: true, description: "Beautifully patterned leaves that fold upward at night like hands in prayer. Fascinating and decorative.", careInstructions: "Keep evenly moist. High humidity preferred. No direct sun — causes fading.", recommendedPlacement: "Tables, shelves, bedrooms", growthSpeed: "Moderate", humidityRequirement: "High", emoji: "🙏", gradient: "from-green-300/20 to-red-400/10", badge: "Pet Safe", popularity: 74 },
  { name: "Spider Plant", scientificName: "Chlorophytum comosum", price: "18.00", category: "Trailing", difficulty: "Easy", lightRequirement: "Medium to bright indirect", wateringFrequency: "Weekly", petSafe: true, airPurificationRating: 5, indoor: true, description: "Cheerful arching leaves with tiny baby spiderettes that dangle on long stems. Great for beginners.", careInstructions: "Water regularly in summer, less in winter. Trim browning tips. Propagate babies in soil or water.", recommendedPlacement: "Hanging baskets, shelves, anywhere", growthSpeed: "Fast", humidityRequirement: "Medium", emoji: "🕷️", gradient: "from-lime-300/20 to-green-500/10", badge: "Pet Safe", popularity: 93 },
  { name: "Monstera Adansonii", scientificName: "Monstera adansonii", price: "45.00", category: "Tropical", difficulty: "Easy", lightRequirement: "Bright indirect", wateringFrequency: "Weekly", petSafe: false, airPurificationRating: 4, indoor: true, description: "Swiss cheese plant with dramatic oval holes. A collector favorite that's easier to care for than deliciosa.", careInstructions: "High humidity preferred. Water when top inch dries. Provide climbing support for larger growth.", recommendedPlacement: "Bright rooms, hanging baskets, moss poles", growthSpeed: "Moderate", humidityRequirement: "High", emoji: "🧀", gradient: "from-green-400/20 to-emerald-600/10", badge: "New Arrival", popularity: 77 },
  { name: "Bamboo Palm", scientificName: "Chamaedorea seifrizii", price: "65.00", category: "Tropical", difficulty: "Easy", lightRequirement: "Low to medium indirect", wateringFrequency: "Weekly", petSafe: true, airPurificationRating: 5, indoor: true, description: "Graceful clustered canes with elegant fronds. Excellent air purifier that thrives in low light.", careInstructions: "Keep soil lightly moist. Mist fronds regularly. Repot every 2-3 years.", recommendedPlacement: "Offices, dark rooms, hallways", growthSpeed: "Moderate", humidityRequirement: "Medium", emoji: "🎋", gradient: "from-green-500/20 to-teal-700/10", badge: "Pet Safe", popularity: 71 },
  { name: "Echeveria", scientificName: "Echeveria elegans", price: "16.00", category: "Succulent", difficulty: "Easy", lightRequirement: "Bright to full sun", wateringFrequency: "Monthly", petSafe: true, airPurificationRating: 1, indoor: true, description: "Rose-shaped succulent rosettes in silvery-blue. Blooms with delicate orange-yellow flowers in spring.", careInstructions: "Full sun or very bright light. Water sparingly, never let sit in water. Well-draining soil essential.", recommendedPlacement: "Sunny windowsills, succulent arrangements", growthSpeed: "Slow", humidityRequirement: "Low", emoji: "🌹", gradient: "from-blue-300/20 to-teal-400/10", badge: "Pet Safe", popularity: 84 },
  { name: "Hoya Carnosa", scientificName: "Hoya carnosa", price: "38.00", category: "Trailing", difficulty: "Easy", lightRequirement: "Bright indirect", wateringFrequency: "Bi-weekly", petSafe: true, airPurificationRating: 3, indoor: true, description: "Waxy heart-shaped leaves with sweetly fragrant star-shaped flowers. A collector gem.", careInstructions: "Allow to dry between waterings. Bright light for flowering. Don't repot unless necessary.", recommendedPlacement: "Hanging baskets, high shelves near windows", growthSpeed: "Moderate", humidityRequirement: "Medium", emoji: "⭐", gradient: "from-pink-300/20 to-rose-400/10", badge: "Pet Safe", popularity: 79 },
  { name: "Pothos Neon", scientificName: "Epipremnum aureum 'Neon'", price: "26.00", category: "Trailing", difficulty: "Easy", lightRequirement: "Medium to bright indirect", wateringFrequency: "Weekly", petSafe: false, airPurificationRating: 4, indoor: true, description: "Electric lime-yellow leaves that glow in any space. The most vibrant member of the pothos family.", careInstructions: "Bright light intensifies the neon color. Water when soil dries. Propagates easily.", recommendedPlacement: "Bright shelves, hanging in windows", growthSpeed: "Fast", humidityRequirement: "Low", emoji: "💛", gradient: "from-yellow-400/20 to-lime-600/10", popularity: 82 },
  { name: "Bromeliad Guzmania", scientificName: "Guzmania lingulata", price: "40.00", category: "Flowering", difficulty: "Easy", lightRequirement: "Medium indirect", wateringFrequency: "Weekly", petSafe: true, airPurificationRating: 3, indoor: true, description: "Dramatic star-shaped flower bracts in brilliant reds and oranges that last for months.", careInstructions: "Fill central cup with water, empty and refill monthly. Keep soil lightly moist. No direct sun.", recommendedPlacement: "Dining tables, living rooms, offices", growthSpeed: "Slow", humidityRequirement: "High", emoji: "🌟", gradient: "from-orange-400/20 to-red-600/10", badge: "Pet Safe", popularity: 68 },
  { name: "Croton", scientificName: "Codiaeum variegatum", price: "34.00", category: "Statement", difficulty: "Moderate", lightRequirement: "Bright direct to indirect", wateringFrequency: "Weekly", petSafe: false, airPurificationRating: 2, indoor: true, description: "Explosively colorful leaves in red, orange, yellow, and green. The most dramatic foliage plant.", careInstructions: "Maximum light for best colors. Keep evenly moist. High humidity. Avoid cold drafts.", recommendedPlacement: "Sunny spots, south-facing windows", growthSpeed: "Moderate", humidityRequirement: "High", emoji: "🎨", gradient: "from-orange-400/20 to-yellow-600/10", popularity: 70 },
  { name: "English Ivy", scientificName: "Hedera helix", price: "20.00", category: "Trailing", difficulty: "Easy", lightRequirement: "Low to bright indirect", wateringFrequency: "Weekly", petSafe: false, airPurificationRating: 4, indoor: true, description: "Classic trailing plant with deeply lobed leaves. Excellent for hanging baskets and climbing structures.", careInstructions: "Allow to slightly dry between waterings. Benefits from cooler temperatures. Prune regularly.", recommendedPlacement: "Hanging baskets, trellises, shelves", growthSpeed: "Fast", humidityRequirement: "Medium", emoji: "🌿", gradient: "from-green-500/20 to-emerald-700/10", popularity: 76 },
  { name: "Parlor Palm", scientificName: "Chamaedorea elegans", price: "42.00", category: "Tropical", difficulty: "Easy", lightRequirement: "Low to medium indirect", wateringFrequency: "Weekly", petSafe: true, airPurificationRating: 4, indoor: true, description: "Elegant Victorian parlor plant with fine arching fronds. Thrives in low light conditions.", careInstructions: "Water when top inch dries. Do not overwater. Tolerates low humidity but prefers medium.", recommendedPlacement: "Offices, hallways, low-light spaces", growthSpeed: "Slow", humidityRequirement: "Medium", emoji: "🌴", gradient: "from-green-400/20 to-teal-600/10", badge: "Pet Safe", popularity: 77 },
  { name: "African Violet", scientificName: "Saintpaulia ionantha", price: "22.00", category: "Flowering", difficulty: "Moderate", lightRequirement: "Bright indirect", wateringFrequency: "Weekly", petSafe: true, airPurificationRating: 2, indoor: true, description: "Compact rosettes with velvety leaves and cheerful purple, pink, or white blooms year-round.", careInstructions: "Bottom water to prevent leaf spotting. Bright indirect light. Remove spent blooms.", recommendedPlacement: "Windowsills, desktops, shelves", growthSpeed: "Slow", humidityRequirement: "Medium", emoji: "💜", gradient: "from-violet-400/20 to-purple-600/10", badge: "Pet Safe", popularity: 74 },
  { name: "Cast Iron Plant", scientificName: "Aspidistra elatior", price: "48.00", category: "Statement", difficulty: "Easy", lightRequirement: "Low to medium indirect", wateringFrequency: "Monthly", petSafe: true, airPurificationRating: 3, indoor: true, description: "Lives up to its name — virtually indestructible. Deep green strap-like leaves in any conditions.", careInstructions: "Incredibly tolerant. Water sparingly, almost any light level works. Can survive extreme neglect.", recommendedPlacement: "Dark corners, offices, hallways", growthSpeed: "Slow", humidityRequirement: "Low", emoji: "🛡️", gradient: "from-green-600/20 to-emerald-800/10", badge: "Pet Safe", popularity: 66 },
  { name: "Nerve Plant", scientificName: "Fittonia albivenis", price: "18.00", category: "Small", difficulty: "Moderate", lightRequirement: "Low to medium indirect", wateringFrequency: "Twice weekly", petSafe: true, airPurificationRating: 2, indoor: true, description: "Intricate white or pink vein patterns on deep green leaves. Stunning miniature foliage for terrariums.", careInstructions: "Keep consistently moist, never allow to wilt. High humidity essential. No direct sun.", recommendedPlacement: "Terrariums, bathrooms, humid spots", growthSpeed: "Moderate", humidityRequirement: "High", emoji: "🕸️", gradient: "from-green-300/20 to-emerald-500/10", badge: "Pet Safe", popularity: 71 },
  { name: "Cactus (Mix)", scientificName: "Cactaceae sp.", price: "15.00", category: "Cactus", difficulty: "Easy", lightRequirement: "Full sun to bright indirect", wateringFrequency: "Monthly", petSafe: false, airPurificationRating: 1, indoor: true, description: "Collection of sculptural desert cacti in varying shapes and sizes. Incredibly low maintenance.", careInstructions: "Maximum sunlight. Water only when completely dry. Excellent drainage is critical.", recommendedPlacement: "Sunny windowsills, south-facing windows", growthSpeed: "Slow", humidityRequirement: "Low", emoji: "🌵", gradient: "from-amber-400/20 to-orange-600/10", popularity: 87 },
  { name: "Alocasia Polly", scientificName: "Alocasia amazonica 'Polly'", price: "52.00", category: "Tropical", difficulty: "Expert", lightRequirement: "Bright indirect", wateringFrequency: "Weekly", petSafe: false, airPurificationRating: 4, indoor: true, description: "Dramatic arrow-shaped leaves with bold white veins on dark green. A striking collector specimen.", careInstructions: "High humidity essential. Water regularly but avoid soggy soil. Watch for spider mites.", recommendedPlacement: "Humid bathrooms, beside humidifiers", growthSpeed: "Moderate", humidityRequirement: "High", emoji: "🏹", gradient: "from-green-700/20 to-emerald-900/10", badge: "Rare Find", popularity: 76 },
  { name: "Dumb Cane", scientificName: "Dieffenbachia seguine", price: "32.00", category: "Tropical", difficulty: "Easy", lightRequirement: "Low to bright indirect", wateringFrequency: "Weekly", petSafe: false, airPurificationRating: 4, indoor: true, description: "Bold tropical foliage with cream and green variegation. Fast-growing and impressively large.", careInstructions: "Water when top inch dries. Tolerates low light but grows faster in medium light. Rotate monthly.", recommendedPlacement: "Living rooms, offices, hallways", growthSpeed: "Fast", humidityRequirement: "Medium", emoji: "🌿", gradient: "from-lime-400/20 to-green-600/10", popularity: 81 },
  { name: "Polka Dot Plant", scientificName: "Hypoestes phyllostachya", price: "16.00", category: "Small", difficulty: "Easy", lightRequirement: "Bright indirect", wateringFrequency: "Twice weekly", petSafe: true, airPurificationRating: 1, indoor: true, description: "Playful pink or red spotted leaves that brighten any desk or terrarium. Compact and cheerful.", careInstructions: "Bright light keeps colors vibrant. Keep consistently moist. Pinch to prevent legginess.", recommendedPlacement: "Desks, terrariums, windowsills", growthSpeed: "Fast", humidityRequirement: "Medium", emoji: "🔴", gradient: "from-pink-400/20 to-rose-600/10", badge: "Pet Safe", popularity: 72 },
  { name: "Umbrella Plant", scientificName: "Schefflera arboricola", price: "44.00", category: "Statement", difficulty: "Easy", lightRequirement: "Medium to bright indirect", wateringFrequency: "Weekly", petSafe: false, airPurificationRating: 4, indoor: true, description: "Glossy umbrella-shaped leaf clusters on upright stems. Tolerant and impressive in any space.", careInstructions: "Allow top inch to dry between waterings. Rotate for even growth. Wipe leaves monthly.", recommendedPlacement: "Living rooms, offices, corners", growthSpeed: "Moderate", humidityRequirement: "Medium", emoji: "☂️", gradient: "from-green-400/20 to-emerald-600/10", popularity: 78 },
  { name: "String of Hearts", scientificName: "Ceropegia woodii", price: "36.00", category: "Trailing", difficulty: "Easy", lightRequirement: "Bright indirect", wateringFrequency: "Bi-weekly", petSafe: true, airPurificationRating: 2, indoor: true, description: "Delicate chains of heart-shaped succulent leaves with silver markings. Romantic and unique.", careInstructions: "Allow to dry between waterings. Bright light for best patterns. Plant in well-draining soil.", recommendedPlacement: "Hanging baskets, high shelves near windows", growthSpeed: "Moderate", humidityRequirement: "Low", emoji: "💕", gradient: "from-pink-300/20 to-purple-500/10", badge: "Pet Safe", popularity: 80 },
  { name: "Yucca", scientificName: "Yucca elephantipes", price: "78.00", category: "Statement", difficulty: "Easy", lightRequirement: "Bright to full sun", wateringFrequency: "Monthly", petSafe: false, airPurificationRating: 3, indoor: true, description: "Bold architectural presence with sword-like leaves. Extremely drought tolerant and long-lived.", careInstructions: "Maximum light. Water deeply but very infrequently. Excellent drainage needed.", recommendedPlacement: "Sunny rooms, south-facing spots", growthSpeed: "Slow", humidityRequirement: "Low", emoji: "🗡️", gradient: "from-lime-500/20 to-green-700/10", popularity: 73 },
  { name: "Philodendron Gloriosum", scientificName: "Philodendron gloriosum", price: "95.00", category: "Rare", difficulty: "Moderate", lightRequirement: "Bright indirect", wateringFrequency: "Weekly", petSafe: false, airPurificationRating: 4, indoor: true, description: "Velvety heart-shaped leaves with striking white veins. A collector's treasure with creeping habit.", careInstructions: "High humidity preferred. Water when top inch dries. Plant in rich, well-draining mix.", recommendedPlacement: "Bright rooms, near humidifiers", growthSpeed: "Slow", humidityRequirement: "High", emoji: "♥️", gradient: "from-emerald-500/20 to-green-700/10", badge: "Rare Find", popularity: 69 },
  { name: "Tradescantia Zebrina", scientificName: "Tradescantia zebrina", price: "18.00", category: "Trailing", difficulty: "Easy", lightRequirement: "Bright indirect", wateringFrequency: "Weekly", petSafe: false, airPurificationRating: 3, indoor: true, description: "Shimmering silver and purple striped leaves on trailing stems. Incredibly fast growing and striking.", careInstructions: "Bright light maintains variegation. Water when top inch dries. Pinch for bushiness.", recommendedPlacement: "Hanging baskets, shelves, tabletops", growthSpeed: "Fast", humidityRequirement: "Medium", emoji: "🦓", gradient: "from-purple-400/20 to-violet-600/10", popularity: 83 },
  { name: "Calathea Rattlesnake", scientificName: "Calathea lancifolia", price: "36.00", category: "Statement", difficulty: "Moderate", lightRequirement: "Medium indirect", wateringFrequency: "Weekly", petSafe: true, airPurificationRating: 3, indoor: true, description: "Long wavy leaves with dark green spots and deep purple undersides. Dramatic and pet-safe.", careInstructions: "Use filtered water. High humidity. Medium light, never direct sun. Keep evenly moist.", recommendedPlacement: "Bathrooms, kitchens, shaded rooms", growthSpeed: "Moderate", humidityRequirement: "High", emoji: "🐍", gradient: "from-green-400/20 to-purple-600/10", badge: "Pet Safe", popularity: 75 },
  { name: "Ponytail Palm", scientificName: "Beaucarnea recurvata", price: "62.00", category: "Statement", difficulty: "Easy", lightRequirement: "Bright to full sun", wateringFrequency: "Monthly", petSafe: true, airPurificationRating: 2, indoor: true, description: "Swollen trunk stores water like a camel. Cascading fountain of curly leaves — sculptural and unique.", careInstructions: "Maximum light. Very infrequent watering — drought tolerant. Well-draining, sandy soil.", recommendedPlacement: "Sunny rooms, south-facing windows", growthSpeed: "Slow", humidityRequirement: "Low", emoji: "🐴", gradient: "from-amber-400/20 to-orange-600/10", badge: "Pet Safe", popularity: 77 },
  { name: "Anthuriums", scientificName: "Anthurium andraeanum", price: "48.00", category: "Flowering", difficulty: "Moderate", lightRequirement: "Bright indirect", wateringFrequency: "Weekly", petSafe: false, airPurificationRating: 3, indoor: true, description: "Glossy heart-shaped spathes in vibrant red, pink, or white. Continuous bloomer in good conditions.", careInstructions: "Bright indirect light for blooms. Water when top inch dries. Mist flowers to extend life.", recommendedPlacement: "Bright offices, living rooms, dining tables", growthSpeed: "Moderate", humidityRequirement: "High", emoji: "❤️", gradient: "from-red-400/20 to-rose-600/10", popularity: 85 },
  { name: "Aglaonema", scientificName: "Aglaonema commutatum", price: "36.00", category: "Tropical", difficulty: "Easy", lightRequirement: "Low to medium indirect", wateringFrequency: "Weekly", petSafe: false, airPurificationRating: 5, indoor: true, description: "Beautifully patterned leaves in various shades of red, pink, and green. Thrives in low light.", careInstructions: "Very tolerant of neglect. Water when top inch dries. Avoid cold drafts.", recommendedPlacement: "Offices, dark corners, hallways", growthSpeed: "Slow", humidityRequirement: "Low", emoji: "🎨", gradient: "from-red-300/20 to-green-500/10", popularity: 86 },
  { name: "Monstera Thai Constellation", scientificName: "Monstera deliciosa 'Thai Constellation'", price: "280.00", originalPrice: "350.00", category: "Rare", difficulty: "Moderate", lightRequirement: "Bright indirect", wateringFrequency: "Weekly", petSafe: false, airPurificationRating: 4, indoor: true, description: "Ultra-rare variegated monstera with cream constellation splashes. The crown jewel of any collection.", careInstructions: "Stable, warm environment. Bright indirect light. Water when top 2 inches dry. High humidity.", recommendedPlacement: "Statement spots in bright rooms", growthSpeed: "Slow", humidityRequirement: "High", emoji: "⭐", gradient: "from-slate-300/20 to-green-500/10", badge: "Ultra Rare", popularity: 65 },
  { name: "Watermelon Peperomia", scientificName: "Peperomia argyreia", price: "22.00", category: "Small", difficulty: "Easy", lightRequirement: "Medium to bright indirect", wateringFrequency: "Weekly", petSafe: true, airPurificationRating: 2, indoor: true, description: "Succulent-like leaves with watermelon stripe patterns. Compact, cute, and virtually pest-resistant.", careInstructions: "Water moderately, allow to dry slightly. No direct sun. Great in terrariums.", recommendedPlacement: "Desktops, windowsills, terrariums", growthSpeed: "Slow", humidityRequirement: "Medium", emoji: "🍉", gradient: "from-green-400/20 to-red-500/10", badge: "Pet Safe", popularity: 84 },
  { name: "Kentia Palm", scientificName: "Howea forsteriana", price: "110.00", category: "Tropical", difficulty: "Easy", lightRequirement: "Low to bright indirect", wateringFrequency: "Weekly", petSafe: true, airPurificationRating: 4, indoor: true, description: "The classic Victorian parlor palm. Slow-growing and extremely elegant with arching dark green fronds.", careInstructions: "Very tolerant of low light. Water when top inch dries. Clean fronds occasionally.", recommendedPlacement: "Living rooms, offices, lobbies", growthSpeed: "Slow", humidityRequirement: "Low", emoji: "🌴", gradient: "from-green-500/20 to-teal-700/10", badge: "Pet Safe", popularity: 78 },
];

async function seed() {
  console.log("Seeding plants...");
  
  // Clear existing plants
  await db.execute(sql`TRUNCATE TABLE plants RESTART IDENTITY CASCADE`);
  
  // Insert all plants
  await db.insert(plantsTable).values(plantsData.map(p => ({
    ...p,
    price: p.price,
    originalPrice: (p as { originalPrice?: string }).originalPrice ?? null,
  })));
  
  console.log(`✅ Seeded ${plantsData.length} plants successfully!`);
  process.exit(0);
}

seed().catch(e => {
  console.error("Seed failed:", e);
  process.exit(1);
});
